name: Template Validation Sample Workflow
on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test_gallery_validation_job:
    runs-on: ubuntu-latest
    name: test gallery validation
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: LianwMS/template-validation-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repositoryURL: https://github.com/Azure-Samples/azd-ai-starter.git
