name: Template Validation Sample Workflow
on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  template_validation_job:
    runs-on: ubuntu-latest
    name: template validation
    steps:
      - uses: actions/checkout@v4
      - id: validation
        uses: LianwMS/template-validation-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repositoryURL: https://github.com/Azure-Samples/azd-ai-starter
      
      - name: print result
        run: cat ${{ steps.validation.outputs.resultFile }}
